# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from menu_ui import Ui_MenuWindow
import sys
sys.path.insert(0, '/home/szymon/Documents/password_manager/backend')
from password_manager import Password_manager



class Ui_MainWindow():
    
    def __init__(self, MainWindow):

        self.setupUi(MainWindow)
        self.password_mistakes = 0
    
    def setupUi(self, MainWindow):

        MainWindow.setObjectName("Password manager-login")
        MainWindow.resize(398, 328)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        #login button
        self.loginButton = QtWidgets.QPushButton(self.centralwidget)
        self.loginButton.setGeometry(QtCore.QRect(150, 150, 101, 31))
        self.loginButton.setObjectName("pushButton")
        self.loginButton.clicked.connect(self.check_password)
        self.loginButton.setAutoDefault(True)

        self.lineEdit_password= QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_password.setGeometry(QtCore.QRect(120, 100, 171, 31))
        self.lineEdit_password.setObjectName("Password")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
    
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(130, 60, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_2")

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 398, 22))
        self.menubar.setObjectName("menubar")
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

        MainWindow.setCentralWidget(self.centralwidget)
        MainWindow.setMenuBar(self.menubar)
        MainWindow.setStatusBar(self.statusbar)
   
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):

        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loginButton.setText(_translate("MainWindow", "Login"))
        self.label_1.setText(_translate("MainWindow", "Enter secret key"))

    def closeEvent(self, app):
        
        answer = QtWidgets.QMessageBox.question(self, 'ATTENTION',
                                      'Are you sure you want to quit?',
                                      QtWidgets.QMessageBox.Yes |
                                      QtWidgets.QMessageBox.No,
                                      QtWidgets.QMessageBox.No)
        if answer == QtWidgets.QMessageBox.Yes:
            app.accept()
        else:
            app.ignore()
            
    def check_password(self):
        
        msg = QtWidgets.QMessageBox()


        if self.lineEdit_password.text() == '1234':
            MainWindow.close()
            widget.show()
            #MenuWindow.show()
        else:
            msg.setText('Incorrect')
            msg.exec_()
            self.lineEdit_password.clear()
            self.password_mistakes+=1

        
        if(self.password_mistakes >= 3):
            sys.exit(app.exec_())




if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle("Fusion")
    #app.setQuitOnLastWindowClosed(False)
    MainWindow = QtWidgets.QMainWindow()
    MenuWindow = QtWidgets.QMainWindow()
    widget = QtWidgets.QStackedWidget()
    Dialog = QtWidgets.QDialog()
    Form = QtWidgets.QWidget()
    Form1 = QtWidgets.QWidget()
    Form2 = QtWidgets.QWidget()
    Form3 = QtWidgets.QWidget()
    Form4 = QtWidgets.QWidget()
    Form5 = QtWidgets.QWidget()
    widget.addWidget(MenuWindow)
    widget.setFixedHeight(602)
    widget.setFixedWidth(782)
    pm = Password_manager()
    ui = Ui_MainWindow(MainWindow)
    ui_menu = Ui_MenuWindow(MenuWindow, Form,Form1, Form2, Form3, Form4, Form5, widget, pm)
    MainWindow.show()
    sys.exit(app.exec_())
    